gridSize = 30 #the height and width of the array of blocks
blockSize = 20 #pixels wide of each block
mapSize = gridSize*blockSize
blockGrid = [[0 for y in range(gridSize)] for x in range(gridSize)] #creates the array for the grid
blockDictionary = ["NormalBlock", "PathBlock","WaterBlock"]
monsterDictionary = ["Monster1", "Monster2","AlexMonster","BenMonster","LeoMonster","MonsterBig"]
towerDictionary = {"Arrow Shooter":"ArrowShooterTower", "Bullet Shooter":"BulletShooterTower", "Tack Tower": "TackTower", "Power Tower": "PowerTower"}
towerCost = {"Arrow Shooter":150,"Bullet Shooter":150,"Tack Tower":150, "Power Tower":200}
towerGrid = [[None for y in range(gridSize)] for x in range(gridSize)]
pathList = []
spawnx = 0
spawny = 0
monsters = []
monstersByHealth = []
monstersByHealthReversed = []
monstersByDistance = []
monstersByDistanceReversed = []
monstersListList = [monstersByHealth,monstersByHealthReversed,monstersByDistance,monstersByDistanceReversed]
projectiles = []
health = 100
money = 5000000000
selectedTower = "<None>"
displayTower = None